/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/harjoitus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hakee listan kaikista harjoituksista (esim. hakua ja selausta varten) */
        get: operations["getHarjoitukset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harjoitus/{harjoitusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hakee yksittäisen harjoituksen perustiedot ja metadatan */
        get: operations["getHarjoitusById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vastaanottaa sensoridataa lennosta */
        post: operations["ingestSensorData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kiihtyvyys/{harjoitusId}/intensiteetti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiihtyvyyden ja g-voimien ikkunoidut keski- ja huippuarvot aikajärjestyksessä */
        get: operations["getHarjoitusIntensiteetti"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/syke/{harjoitusId}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sykealueiden ajallinen jakauma */
        get: operations["getSykeAlueet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harjoitus/{harjoitusId}/yhteenveto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harjoituksen kokonaisyhteenveto */
        get: operations["getHarjoitusYhteenveto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HarjoitusPerustieto: {
            /** @example workout-uuid-001 */
            harjoitusId: string;
            /** @example Cycling */
            sportType: string;
            /**
             * Format: date-time
             * @example 2024-03-20T12:00:00Z
             */
            startTime: string;
            /**
             * @example COMPLETED
             * @enum {string}
             */
            status: "ACTIVE" | "COMPLETED" | "FAILED";
            /** @example Keskiviikon lenkki keskuspuistossa */
            description?: string;
        };
        SensorData: {
            /** @example workout-uuid-001 */
            harjoitusId: string;
            /** @example 0.12 */
            xCoord?: number;
            /** @example -0.98 */
            yCoord?: number;
            /** @example 0.05 */
            zCoord?: number;
            /** @example 145 */
            pulse?: number;
            /**
             * Format: date-time
             * @example 2024-03-20T12:00:00Z
             */
            timestamp?: string;
        };
        IntensiteettiIkkunaKooste: {
            /**
             * Format: date-time
             * @description Aikajakson alkamisaika
             * @example 2024-03-20T12:00:00Z
             */
            windowStart: string;
            /**
             * Format: date-time
             * @description Aikajakson päättymisaika
             * @example 2024-03-20T12:05:00Z
             */
            windowEnd: string;
            /**
             * Format: double
             * @description Viiden minuutin ikkunan keskikiihtyvyys (G-voima)
             * @example 1.05
             */
            avgGForce: number;
            /**
             * Format: double
             * @description Ikkunan aikana mitattu suurin yksittäinen g-voimapiikki
             * @example 3.82
             */
            maxGForce: number;
            /**
             * @description Databricksissä laskettu kuormitusluokitus tälle jaksolle
             * @example HIGH
             * @enum {string}
             */
            exertionLevel: "LOW" | "MEDIUM" | "HIGH" | "ULTRA";
        };
        PulssialueKooste: {
            /** @example Aerobic */
            zoneName?: string;
            /** @example 1500 */
            secondsInZone?: number;
        };
        /** @description Harjoituksen jälkeinen loppuyhteenveto */
        HarjoitusYhteenveto: {
            /** @example workout-001 */
            harjoitusId: string;
            /**
             * Format: int64
             * @example 270
             */
            totalDurationSeconds: number;
            /**
             * Format: double
             * @example 1000
             */
            totalDistanceMeters: number;
            /**
             * Format: double
             * @example 35
             */
            totalElevationGain: number;
            /**
             * Format: int64
             * @example 99
             */
            climbingDurationSeconds: number;
            /** @example 190 */
            maxPulse: number;
            /**
             * Format: double
             * @example 155.5
             */
            avgPulse: number;
            /**
             * Format: double
             * @example 3.5
             */
            averageSlopePercentage: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHarjoitukset: {
        parameters: {
            query?: {
                /** @description Palautettavien harjoitusten maksimimäärä */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onnistunut haku, palauttaa listan harjoituksista */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarjoitusPerustieto"][];
                };
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHarjoitusById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                harjoitusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onnistunut haku, palauttaa harjoituksen tiedot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarjoitusPerustieto"];
                };
            };
            /** @description Harjoitusta ei löytynyt */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingestSensorData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorData"][];
            };
        };
        responses: {
            /** @description Data lähetetty onnistuneesti Event Hubiin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHarjoitusIntensiteetti: {
        parameters: {
            query?: {
                /** @description Aikajakson pituus minuutteina (oletus 5 min) */
                windowSize?: "1m" | "5m" | "15m" | "30m";
            };
            header?: never;
            path: {
                harjoitusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onnistunut haku, palauttaa listan ikkunoiduista koosteista */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntensiteettiIkkunaKooste"][];
                };
            };
            /** @description Harjoitusta ei löytynyt */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSykeAlueet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                harjoitusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onnistunut haku pulssialueista */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulssialueKooste"][];
                };
            };
            /** @description Harjoitusta ei löytynyt */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHarjoitusYhteenveto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                harjoitusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise summary data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarjoitusYhteenveto"];
                };
            };
            /** @description Harjoitusta ei löytynyt */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sisäinen palvelinvirhe */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
